[build]
  publish = "dist"
  command = "pnpm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "dist"
